version: "3"
services:
  opensearch:
    labels:
      - traefik.enable=true
      - traefik.http.routers.search.rule=Host(`search.${HOST}`)        
      - traefik.http.services.search.loadbalancer.server.port=9200
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms8g -Xmx8g" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    volumes:
      - ./opensearch-security/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
    restart: always

  opensearch-dashboards:
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboards.rule=Host(`${HOST}`)        
      - traefik.http.services.dashboards.loadbalancer.server.port=5601
    restart: always

  traefik:
    image: "traefik:v2.4"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.toml:/etc/traefik/traefik.toml"
    restart: always
